var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/[region]/[industry]/[form]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0p1oekm._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0x_r9c9.js")
R.c("server/chunks/ssr/node_modules_0ev7kv1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1ypm6fc._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ab8gwa._.js")
R.c("server/chunks/ssr/node_modules_next_dist_172hvm-._.js")
R.c("server/chunks/ssr/_1a9eyz9._.js")
R.c("server/chunks/ssr/_07owt46._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0p8s4lh._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_[region]_[industry]_[form]_page_actions_0z04ar3.js")
R.m(39794)
module.exports=R.m(39794).exports
