var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/privacy/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0z2q-88._.js")
R.c("server/chunks/ssr/node_modules_0ev7kv1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1xml2rf.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ab8gwa._.js")
R.c("server/chunks/ssr/node_modules_next_dist_172hvm-._.js")
R.c("server/chunks/ssr/_1a9eyz9._.js")
R.c("server/chunks/ssr/_07owt46._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0p8s4lh._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_privacy_page_actions_0_hxzrk.js")
R.m(25283)
module.exports=R.m(25283).exports
