import type { Metadata } from "next";
import { ArrowRight, Globe, FileText } from "lucide-react";
import formsDb from "@/src/data/forms-db.json";

export const metadata: Metadata = {
  title: "Full Form Directory — All Canadian Legal Forms | CanadianForms.ca",
  description:
    "Browse all 56 combinations of Canadian legal forms across 7 provinces and federal jurisdiction. Find articles of incorporation, shareholder agreements, commercial leases, and more.",
  keywords: [
    "Canadian legal forms directory",
    "corporate forms Canada",
    "articles of incorporation by province",
    "business forms Ontario Alberta BC",
  ],
};

function toTitleCase(slug: string): string {
  return slug
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

const regionColors: Record<string, string> = {
  ontario: "bg-red-50 border-red-100 text-red-700",
  alberta: "bg-blue-50 border-blue-100 text-blue-700",
  "british-columbia": "bg-green-50 border-green-100 text-green-700",
  "nova-scotia": "bg-purple-50 border-purple-100 text-purple-700",
  manitoba: "bg-amber-50 border-amber-100 text-amber-700",
  saskatchewan: "bg-orange-50 border-orange-100 text-orange-700",
  federal: "bg-slate-100 border-slate-200 text-slate-700",
};

const regionFlags: Record<string, string> = {
  ontario: "🔴",
  alberta: "🔵",
  "british-columbia": "🟢",
  "nova-scotia": "🟣",
  manitoba: "🟡",
  saskatchewan: "🟠",
  federal: "🍁",
};

export default function DirectoryPage() {
  const totalForms = formsDb.regions.length * formsDb.forms.length;

  return (
    <div className="min-h-screen bg-slate-50">
      {/* Header */}
      <section className="bg-white border-b border-slate-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16 text-center">
          <div className="inline-flex items-center gap-2 bg-blue-50 border border-blue-100 text-blue-700 text-xs font-semibold px-4 py-2 rounded-full mb-6">
            <Globe className="w-4 h-4" />
            Complete Form Index
          </div>
          <h1 className="text-4xl sm:text-5xl font-extrabold text-slate-900 leading-tight mb-4">
            Browse All Canadian Legal Forms
          </h1>
          <p className="text-xl text-slate-600 max-w-2xl mx-auto">
            {totalForms} form combinations across {formsDb.regions.length} provinces and federal jurisdiction. Each generated by AI for your specific location.
          </p>

          {/* Stats */}
          <div className="flex flex-wrap items-center justify-center gap-8 mt-10">
            <div className="text-center">
              <div className="text-3xl font-extrabold text-blue-600">{formsDb.regions.length}</div>
              <div className="text-slate-500 text-sm mt-1">Jurisdictions</div>
            </div>
            <div className="w-px h-12 bg-slate-200 hidden sm:block" />
            <div className="text-center">
              <div className="text-3xl font-extrabold text-blue-600">{formsDb.forms.length}</div>
              <div className="text-slate-500 text-sm mt-1">Document Types</div>
            </div>
            <div className="w-px h-12 bg-slate-200 hidden sm:block" />
            <div className="text-center">
              <div className="text-3xl font-extrabold text-blue-600">{totalForms}</div>
              <div className="text-slate-500 text-sm mt-1">Total Form Combinations</div>
            </div>
            <div className="w-px h-12 bg-slate-200 hidden sm:block" />
            <div className="text-center">
              <div className="text-3xl font-extrabold text-blue-600">$49</div>
              <div className="text-slate-500 text-sm mt-1">Flat per Document</div>
            </div>
          </div>
        </div>
      </section>

      {/* Form Grid by Region */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">

        {/* Quick Navigation */}
        <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-6 mb-12">
          <h2 className="text-sm font-semibold text-slate-500 uppercase tracking-wider mb-4">Jump to Province</h2>
          <div className="flex flex-wrap gap-3">
            {formsDb.regions.map((region) => (
              <a
                key={region}
                href={`#${region}`}
                className={`inline-flex items-center gap-1.5 px-4 py-2 rounded-xl text-sm font-medium border transition-all hover:shadow-sm ${regionColors[region] || "bg-slate-50 border-slate-200 text-slate-700"}`}
              >
                <span>{regionFlags[region]}</span>
                {toTitleCase(region)}
              </a>
            ))}
          </div>
        </div>

        {/* Region Sections */}
        <div className="space-y-12">
          {formsDb.regions.map((region) => (
            <section key={region} id={region} className="scroll-mt-24">
              {/* Region Header */}
              <div className="flex items-center gap-4 mb-6">
                <div className={`inline-flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-bold border ${regionColors[region] || "bg-slate-50 border-slate-200 text-slate-700"}`}>
                  <span className="text-lg">{regionFlags[region]}</span>
                  {toTitleCase(region)}
                </div>
                <div className="flex-1 h-px bg-slate-200" />
                <span className="text-sm text-slate-500 whitespace-nowrap">
                  {formsDb.forms.length} forms available
                </span>
              </div>

              {/* Form Links Grid */}
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                {formsDb.forms.map((form) => (
                  <a
                    key={form}
                    href={`/${region}/${form}`}
                    className="group bg-white rounded-xl border border-slate-100 p-5 hover:border-blue-200 hover:shadow-md transition-all flex flex-col justify-between min-h-[120px]"
                  >
                    <div className="flex items-start gap-3 mb-3">
                      <div className="w-8 h-8 bg-slate-50 rounded-lg flex items-center justify-center flex-shrink-0 group-hover:bg-blue-50 transition-colors">
                        <FileText className="w-4 h-4 text-slate-400 group-hover:text-blue-500 transition-colors" />
                      </div>
                      <span className="text-sm font-semibold text-slate-600 group-hover:text-blue-600 transition-colors leading-snug">
                        {toTitleCase(form)}
                      </span>
                    </div>
                    <div className="flex items-center gap-1 text-xs text-slate-400 group-hover:text-blue-500 transition-colors">
                      <span>Generate for $49</span>
                      <ArrowRight className="w-3 h-3 group-hover:translate-x-1 transition-transform" />
                    </div>
                  </a>
                ))}
              </div>
            </section>
          ))}
        </div>

        {/* Bottom CTA */}
        <div className="mt-16 bg-blue-600 rounded-3xl p-10 text-center text-white">
          <h2 className="text-3xl font-extrabold mb-4">
            Can&apos;t find your form?
          </h2>
          <p className="text-blue-200 text-lg mb-8">
            Our AI can generate custom legal documents for any Canadian jurisdiction. Get in touch.
          </p>
          <a
            href="/"
            className="inline-flex items-center gap-2 bg-white text-blue-600 font-bold px-8 py-4 rounded-xl hover:bg-blue-50 transition-colors text-lg"
          >
            Back to Search
            <ArrowRight className="w-5 h-5" />
          </a>
        </div>
      </div>
    </div>
  );
}
